language: android
before_install:
  - wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
  - unzip gradle-1.6-bin.zip
  - export GRADLE_HOME=$PWD/gradle-1.6
  - export PATH=$GRADLE_HOME/bin:$PATH
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra
    - add-on
    # - extra-google-google_play_services
    # - extra-android-support
    # - addon-google_apis-google-21
    # - extra-android-m2repository
    # - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
